[dev]
  publish = "."

[[redirects]]
from = "/login"
to = "/login"
status = 200

[[redirects]]
from = "/*"
to = "/one/:splat"
status = 200
force = true
conditions = { Role = ["admin"] }

[[redirects]]
from = "/*"
to = "/login"
status = 302
